In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

ERROR: Error in parse(text = x, srcfile = src): <text>:5:8: unexpected symbol
4: 
5: import numpy
          ^


In [ ]:
2+3


In [ ]:
6/3

In [ ]:
(3+8)/(2+3)

In [ ]:
log(12)

In [ ]:
sqrt(121)

In [7]:
x=1:10
cat(x)
cat('Mean of x is ',mean(x))
cat('Median of x is ',median(x))
cat('Variance of x is ',var(x))
cat('Standard Deviation of x is ',sd(x))


1 2 3 4 5 6 7 8 9 10Mean of x is  5.5Median of x is  5.5Variance of x is  9.166667Standard Deviation of x is  3.02765

In [8]:
cat(x, '\n')
cat('Mean of x is ',mean(x),'\n')
cat('Median of x is ',median(x),'\n')
cat('Variance of x is ',var(x),'\n')
cat('Standard Deviation of x is ',sd(x),'\n')


1 2 3 4 5 6 7 8 9 10 
Mean of x is  5.5 
Median of x is  5.5 
Variance of x is  9.166667 
Standard Deviation of x is  3.02765 


In [9]:
print(x)
print(paste('Mean of x is ',mean(x)))
print(paste('Median of x is ',median(x)))
print(paste('Variance of x is ',var(x)))
print(paste('Standard Deviation of x is ',sd(x)))

 [1]  1  2  3  4  5  6  7  8  9 10
[1] "Mean of x is  5.5"
[1] "Median of x is  5.5"
[1] "Variance of x is  9.16666666666667"
[1] "Standard Deviation of x is  3.02765035409749"


In [10]:
x=8+7
x

[1] 15

In [11]:
#Creation of character variable
x = "Dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "Dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [12]:
x = 23L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [13]:
x = 2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [14]:
x = TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] TRUE

[1] "logical"

[1] "logical"

[1] 1

NULL

In [15]:
vector() #An empty 'logical' vector

logical(0)

In [17]:
vector("character", length=5)#A vector of mode 'character' with 5 elements

[1] "" "" "" "" ""

In [18]:
character(5) #Same thing but using the constructor directly

[1] "" "" "" "" ""

In [19]:
numeric(5)#Numeric vector with 5 elements

[1] 0 0 0 0 0

In [20]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [22]:
x = c(2,3,4,5,6)

In [23]:
x
class(x)

[1] 2 3 4 5 6

[1] "numeric"

In [25]:
x = c(2L,3L,4L,5L,6L)
x
class(x)
length(x)

[1] 2 3 4 5 6

[1] "integer"

[1] 5

In [27]:
y = c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [28]:
z = c("Tracy","Sarah","Jon")
z
class(z)
length(z)

[1] "Tracy" "Sarah" "Jon"

[1] "character"

[1] 3

In [29]:
#Adding elements at the end
print("Elements in z before")
z
z = c(z,"Annette")
print("Elements in z after")
z

[1] "Elements in z before"


[1] "Tracy" "Sarah" "Jon"

[1] "Elements in z after"


[1] "Tracy"   "Sarah"   "Jon"     "Annette"

In [30]:
a = 1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [31]:
seq(from =1,to = 10, by=0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [32]:
1/0

[1] Inf

In [33]:
0/0


[1] NaN

In [34]:
exp(Inf)

[1] Inf

In [35]:
exp(-Inf)

[1] 0

In [36]:
Inf-Inf

[1] NaN

In [37]:
log(0)
log(1)

[1] -Inf

[1] 0

In [38]:
a = c(1.7, "a")
a

[1] "1.7" "a"

In [39]:
b = c(TRUE,2,3,FALSE)
b

[1] 1 2 3 0

In [44]:
c = c("a",TRUE)
c

[1] "a"    "TRUE"

In [45]:
#Explicit Type Conversion
as.numeric("1")


[1] 1

In [46]:
as.numeric(c("45","66"))

[1] 45 66

In [47]:
as.numeric(c("45","66","six"))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [48]:
as.character(22)

[1] "22"

In [49]:
as.character(c(22,33,44))

[1] "22" "33" "44"

In [50]:
#Matrix
m = matrix(nrow=2, ncol=5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA

In [51]:
dim(m)

[1] 2 5

In [52]:
class(m)

[1] "matrix"

In [55]:
m = matrix(c(1:3))
print("Given Matrix is:")
print(m)
print("Dimentions of the given Matrix")
print(dim(m))
print("Class of te given Matrix")
print(class(m))
print("Type og given Matrix")
print(typeof(m))

[1] "Given Matrix is:"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "Dimentions of the given Matrix"
[1] 3 1
[1] "Class of te given Matrix"
[1] "matrix"
[1] "Type og given Matrix"
[1] "integer"


In [57]:
a = matrix(1:6,nrow=2,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [59]:
m = 1:10
print(m)
print(dim(m))
dim(m) = c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [62]:
my_name <-readline(prompt="Enter Name: ")
my_age <-readline(prompt="Enter Age: ")
#convert character into integer
my_age = as.integer(my_age)
print(paste("Hi ",my_name," next year you will be ",my_age+1," Years old!"))

Enter Name: Praveen
Enter Age: 18
[1] "Hi  Praveen  next year you will be  19  Years old!"


In [63]:
w = readline()
w

Hey There!


[1] "Hey There!"